services:
  
type: web
  name: finansalud-crypto-api
  env: python
  buildCommand: pip install -r requirements.txt
  startCommand: python main.py
  envVars:
key: ENVIRONMENT
    value: production
key: PORT
  value: 10000
